const NAVLIST = document.querySelector(".main-nav__list")
const NAVTOGGLE = document.querySelector(".main-nav__toggle")
const NAVLOGO = document.querySelector(".main-nav__logo-link")
const MAP = document.querySelector(".contacts__map-frame1")
const PAGEHEADER = document.querySelector(".page_header")

NAVLOGO.classList.remove("main-nav__logo-link--mod")
PAGEHEADER.classList.add("page_header--js")
NAVTOGGLE.classList.add("main-nav__toggle--js")
NAVTOGGLE.classList.add("main-nav__toggle--closed-js")
NAVTOGGLE.classList.remove("main-nav__toggle--open-js")
NAVLIST.classList.add("main-nav__list--closed-js")
MAP.classList.add("contacts__map-frame--js")

NAVTOGGLE.addEventListener("click", () => {
  NAVTOGGLE.classList.toggle("main-nav__toggle--closed-js")
  NAVTOGGLE.classList.toggle("main-nav__toggle--open-js")
  NAVLIST.classList.toggle("main-nav__list--closed-js")
  NAVLOGO.classList.toggle("main-nav__logo-link--mod")
})
